from decouple import config


POSTGRES_DB = config('POSTGRES_DB')
POSTGRES_PORT = config('POSTGRES_PORT')
POSTGRES_HOST = config('POSTGRES_HOST')
POSTGRES_USER = config('POSTGRES_USER')
POSTGRES_PASSWORD = config('POSTGRES_PASSWORD')

QT_MAX_REGISTROS_MES= config('QT_MAX_REGISTROS_MES')
