"""Cria relacionamento entre tabela contas a pagar e receber e cliente fornecedor

Revision ID: 163814092cef
Revises: 021e82c8757a
Create Date: 2023-08-30 15:22:22.124105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163814092cef'
down_revision = '021e82c8757a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_pagar_e_receber', sa.Column('fornecedor_cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas_pagar_e_receber', 'fornecedor_cliente', ['fornecedor_cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas_pagar_e_receber', type_='foreignkey')
    op.drop_column('contas_pagar_e_receber', 'fornecedor_cliente_id')
    # ### end Alembic commands ###
