"""Adiciona colunas de controle de baixa das contas

Revision ID: 27291ab81807
Revises: 4d749f38372d
Create Date: 2023-09-04 10:37:02.026934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27291ab81807'
down_revision = '4d749f38372d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
