"""mudar tipo coluna data_baixa

Revision ID: 62c5baa0ea70
Revises: 9001661364f3
Create Date: 2023-09-05 17:58:49.453107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c5baa0ea70'
down_revision = '9001661364f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.execute('alter table contas_pagar_e_receber alter column data_baixa type date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
