"""Adiciona coluna data_previsao

Revision ID: 9001661364f3
Revises: 27291ab81807
Create Date: 2023-09-05 17:29:36.749295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9001661364f3'
down_revision = '27291ab81807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('contas_pagar_e_receber', sa.Column('data_previsao', sa.Date(), nullable=True))
    # op.execute('update contas_pagar_e_receber set data_previsao = now()')
    # op.alter_column('contas_pagar_e_receber', 'data_previsao', nullable=False)
    op.execute('alter table contas_pagar_e_receber alter column data_baixa type date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('contas_pagar_e_receber', 'data_previsao')
    # op.execute('alter table contas_pagar_e_receber alter column data_baixa type timestamp')
    # ### end Alembic commands ###
    pass
