"""coluna data_baixa tipo date

Revision ID: c310d2a186d6
Revises: 62c5baa0ea70
Create Date: 2023-09-05 18:12:37.002664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c310d2a186d6'
down_revision = '62c5baa0ea70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table contas_pagar_e_receber alter column data_baixa type date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
