"""Atualizando modelo db

Revision ID: ca3e7a2a09ec
Revises: c310d2a186d6
Create Date: 2023-09-06 11:12:56.988931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3e7a2a09ec'
down_revision = 'c310d2a186d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table contas_pagar_e_receber alter column data_baixa type date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
